"""empty message

Revision ID: f0b8d2cbd75e
Revises: 
Create Date: 2024-05-13 22:02:17.425263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0b8d2cbd75e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mercado_sql', schema=None) as batch_op:
        batch_op.drop_index('id')

    op.drop_table('mercado_sql')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mercado_sql',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('descricao', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('categoria', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('mercado_sql', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    op.drop_table('usuario')
    # ### end Alembic commands ###
