"""empty message

Revision ID: d56aca5db463
Revises: a1e73a8d2bf8
Create Date: 2024-05-03 18:52:00.553570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd56aca5db463'
down_revision = 'a1e73a8d2bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor_formacao',
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('formacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formacao_id'], ['formacao.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('professor_id', 'formacao_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professor_formacao')
    # ### end Alembic commands ###
